spring:
  # LOCAL DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}


  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  output:
    ansi:
      enabled: always

admin:
  key: ${ADMIN_KEY}