jwt:
  secret:
    k1AuBqN@3A^D3&39FO7Z!yP2Qz4m+`XiT
spring:
  # LOCAL DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/test
    password: 1234


  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  output:
    ansi:
      enabled: always
